#!/bin/sh
set -eu

repo_root="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"
docs_dir="$repo_root/doc"
index_file="$docs_dir/index.md"
tmp_file="$(mktemp "$docs_dir/.index.XXXXXX")"

cleanup() {
  rm -f "$tmp_file"
}
trap cleanup EXIT INT TERM

{
  printf '%s\n' '# Project Documentation Index'
  printf '%s\n\n' '> Generated by `tool/build_doc_index.sh`; do not edit this file manually.'
  printf '%s\n\n' 'Use this index to find stable project documentation before changing architecture, build tooling, or feature workflows.'

  find "$docs_dir" -maxdepth 1 -type f -name '*.md' ! -name 'index.md' -print \
    | LC_ALL=C sort \
    | while IFS= read -r file; do
        name="$(basename "$file")"
        title="$(sed -n 's/^# //p' "$file" | head -n 1)"
        [ -n "$title" ] || title="$name"
        summary="$(awk 'NF && $0 !~ /^#/ && $0 !~ /^>/ && $0 !~ /^```/ { print; exit }' "$file")"
        printf '%s' "- [$title]($name)"
        [ -n "$summary" ] && printf ' — %s' "$summary"
        printf '\n'
      done
} > "$tmp_file"

mv "$tmp_file" "$index_file"
trap - EXIT INT TERM
